# 고유값 & 고유벡터

행렬 A를 선형변환으로 봤을 때, 선형변환 A에 의한 변환 결과가 자기 자신의 상수배가 되는 0이 아닌 벡터를 고유벡터(eigenvector)라 하고 이 상수배 값을 고유값(eigenvalue)라 한다.
(정방행렬에만 적용가능)

https://angeloyeo.github.io/2019/07/17/eigen_vector.html

In [25]:
import numpy as np
a=np.array([[2,1],[1,2]])
b=np.array([[1],[1]])

In [26]:
a

array([[2, 1],
       [1, 2]])

In [27]:
b

array([[1],
       [1]])

In [28]:
a@b

array([[3],
       [3]])

PCA에 적용

https://angeloyeo.github.io/2019/07/27/PCA.html#fn:2

의문

1. 왜 분산이 데이터를 대표하는가?

https://darkpgmr.tistory.com/110

2. 왜 분산이 큰 피쳐의 방향으로 하는가?

https://m.blog.naver.com/PostView.nhn?blogId=hancury&logNo=221215245092&proxyReferer=https:%2F%2Fwww.google.com%2F

# 특이값 분해

직교하는 벡터 집합에 대하여, 선형 변환 후에 그 크기는 변하지만 여전히 직교할 수 있게
되는 그 직교 집합은 무엇인가? 그리고 선형 변환 후의 결과는 무엇인가?

행렬의 특이값이란 이 행렬로 표현되는 선형변환의 스케일 변환을 나타내는 값으로 해석할 수 있다. 

https://leebaro.tistory.com/entry/SVD%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%B6%94%EC%B2%9C-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0